package wordlists

// DockerNames is a list of scientist and mathematician surnames
// used in docker-style names (e.g. modest_einstein).
var DockerNames = []string{
	"albattani", "allen", "almeida", "antonelli", "archimedes",
	"ardinghelli", "aryabhata", "austin", "babbage", "banach",
	"banzai", "bardeen", "bartik", "bassi", "beaver",
	"bell", "benz", "bhabha", "bhaskara", "black",
	"blackburn", "blackwell", "bohr", "booth", "borg",
	"bose", "bouman", "boyd", "brahmagupta", "brattain",
	"brown", "buck", "burnell", "cannon", "carson",
	"cartwright", "carver", "cauchy", "cerf", "chandrasekhar",
	"chaplygin", "chatelet", "chatterjee", "chebyshev", "clarke",
	"cohen", "colden", "cori", "cray", "curie",
	"curran", "darwin", "davinci", "dewdney", "dhawan",
	"diffie", "dijkstra", "dirac", "driscoll", "dubinsky",
	"easley", "edison", "einstein", "elgamal", "elion",
	"ellis", "engelbart", "euclid", "euler", "faraday",
	"feistel", "fermat", "fermi", "feynman", "fibonacci",
	"fleming", "franklin", "gagarin", "galileo", "galois",
	"ganguly", "gates", "gauss", "germain", "goldberg",
	"goldstine", "goldwasser", "golick", "goodall", "gould",
	"greider", "grothendieck", "haibt", "hamilton", "haslett",
	"hawking", "hellman", "heisenberg", "hermann", "herschel",
	"hertz", "heyrovsky", "hodgkin", "hofstadter", "hoover",
	"hopper", "hugle", "hypatia", "ishizaka", "jackson",
	"jang", "jemison", "jennings", "jepsen", "johnson",
	"joliot", "jones", "kalam", "kapitsa", "kare",
	"keldysh", "keller", "kepler", "khayyam", "kilby",
	"kirch", "knuth", "kowalevski", "lalande", "lamarr",
	"lamport", "leakey", "leavitt", "lederberg", "lehmann",
	"lewin", "lichterman", "liskov", "lovelace", "lumiere",
	"mahavira", "margulis", "matsumoto", "maxwell", "mayer",
	"mccarthy", "mcclintock", "mclean", "mcnulty", "mendel",
	"mendeleev", "merkle", "mestorf", "mirzakhani", "morse",
	"moser", "napier", "nash", "neumann", "newton",
	"nightingale", "nobel", "noether", "northcutt", "noyce",
	"panini", "pare", "pascal", "pasteur", "payne",
	"perlman", "pike", "poincare", "poitras", "proskuriakova",
	"ptolemy", "raman", "ramanujan", "rhodes", "ride",
	"ritchie", "robinson", "roentgen", "rosalind", "rubin",
	"saha", "sammet", "sanderson", "satoshi", "shamir",
	"shannon", "shaw", "shirley", "shockley", "shtern",
	"sinoussi", "snyder", "solomon", "spence", "stonebraker",
	"sutherland", "swartz", "swirles", "taussig", "tesla",
	"tharp", "thompson", "torvalds", "turing", "varahamihira",
	"vaughan", "villani", "visvesvaraya", "volnit", "wescoff",
	"wilbur", "wiles", "williams", "williamson", "wilson",
	"wing", "wozniak", "wright", "wu", "yalow",
	"yonath", "zhukovsky",
}
