// Package wordlists provides word lists used by the words service.
package wordlists

// Random is a general-purpose English word list (~200 common words).
// Extend this list to improve variety.
var Random = []string{
	"able", "acid", "aged", "also", "area", "army", "away", "baby",
	"back", "ball", "band", "bank", "base", "bath", "bear", "beat",
	"been", "bell", "best", "bill", "bird", "blow", "blue", "boat",
	"body", "bomb", "bond", "bone", "book", "born", "both", "bowl",
	"bulk", "burn", "busy", "call", "calm", "came", "card", "care",
	"case", "cash", "cast", "cave", "city", "clad", "clay", "clip",
	"club", "coal", "coat", "code", "coil", "cold", "come", "cook",
	"cool", "cope", "copy", "core", "corn", "cost", "coup", "crew",
	"crop", "cube", "cure", "cute", "damp", "dark", "data", "date",
	"dawn", "days", "dead", "deal", "dean", "dear", "debt", "deep",
	"deny", "desk", "diet", "dirt", "disc", "dish", "disk", "dome",
	"done", "door", "dose", "dots", "down", "draw", "drop", "drum",
	"dual", "dumb", "dump", "dune", "dusk", "dust", "each", "earn",
	"ease", "east", "edge", "else", "emit", "epic", "even", "ever",
	"evil", "exam", "face", "fact", "fail", "fall", "farm", "fast",
	"felt", "file", "fill", "film", "find", "fine", "fire", "firm",
	"fish", "flag", "flat", "flew", "flow", "foam", "fold", "folk",
	"fond", "font", "food", "fool", "fore", "fork", "form", "fort",
	"foul", "free", "from", "fuel", "full", "fund", "fuse", "gale",
	"gate", "gear", "gift", "give", "glad", "glow", "glue", "goal",
	"goes", "gold", "golf", "good", "gore", "gust", "half", "hall",
	"halt", "hand", "hang", "hard", "harm", "harp", "hash", "haul",
	"have", "hawk", "head", "heat", "heel", "held", "help", "herb",
	"here", "hero", "high", "hill", "hint", "hold", "hole", "holy",
	"home", "hope", "horn", "host", "hour", "huge", "hull", "hump",
	"hunt", "hurt", "idea", "idle", "inch", "into", "iron", "isle",
	"item", "join", "jump", "just", "keen", "keep", "kind", "king",
	"knot", "know", "lack", "lake", "lamp", "land", "lane", "last",
	"late", "lava", "lawn", "lead", "leaf", "lean", "left", "lens",
	"lend", "less", "lick", "life", "lift", "like", "lime", "line",
	"link", "lion", "list", "live", "load", "lock", "loft", "long",
	"look", "loop", "lore", "loss", "loud", "love", "luck", "lush",
	"made", "mail", "main", "make", "male", "mall", "many", "mark",
	"mars", "mast", "mate", "math", "maze", "meal", "mean", "meet",
	"melt", "menu", "mere", "mesh", "mild", "mile", "milk", "mill",
	"mind", "mine", "mint", "miss", "mist", "mode", "moon", "more",
	"most", "move", "much", "mute", "myth", "name", "near", "neat",
	"need", "nest", "news", "next", "nice", "node", "none", "noon",
	"norm", "note", "noun", "oath", "odds", "once", "only", "open",
	"oval", "over", "pace", "pack", "page", "pain", "pair", "pale",
	"palm", "park", "part", "pass", "path", "pave", "peak", "peel",
	"peer", "pile", "pine", "pipe", "plan", "play", "plot", "plow",
	"plum", "plus", "poem", "poet", "pole", "poll", "pond", "pool",
	"poor", "port", "pose", "post", "pour", "prey", "prod", "pull",
	"pump", "pure", "push", "race", "rack", "rage", "rail", "rain",
	"rank", "rare", "rate", "rays", "read", "real", "reef", "reel",
	"rely", "rent", "rest", "rich", "ride", "rift", "ring", "rise",
	"risk", "road", "roam", "role", "roll", "roof", "root", "rope",
	"rose", "ruin", "rule", "rush", "rust", "safe", "sage", "sail",
	"sake", "sale", "salt", "same", "sand", "save", "scan", "seal",
	"seed", "self", "sell", "send", "shed", "ship", "shop", "show",
	"side", "sift", "sign", "silk", "silo", "sink", "site", "size",
	"skin", "skip", "slab", "slam", "slim", "slip", "slot", "slow",
	"slum", "snap", "snow", "soak", "soar", "sock", "soft", "soil",
	"sole", "song", "soul", "span", "spin", "spot", "star", "stay",
	"stem", "step", "stir", "stop", "stub", "such", "suit", "sway",
	"swim", "tail", "take", "tale", "tall", "tank", "tape", "task",
	"team", "tell", "term", "test", "text", "than", "that", "then",
	"thin", "this", "tidy", "tier", "tile", "time", "tiny", "toll",
	"tomb", "tone", "tool", "tour", "town", "tree", "trim", "trip",
	"true", "tube", "tune", "turf", "turn", "twin", "type", "upon",
	"used", "user", "vary", "vast", "view", "vine", "void", "vote",
	"wade", "wake", "walk", "wall", "wand", "ward", "warm", "warp",
	"wave", "weak", "weld", "well", "wide", "wild", "will", "wind",
	"wire", "wish", "with", "word", "work", "worn", "wrap", "yard",
	"year", "zone",
}
